version: "3.9"

services:
  simple_oidc_ids6_e2e_test_app:
    container_name: simple_oidc_ids6_e2e_test_app
    image: kbalazsworks/simple_oidc_ids6_e2e_test:master
    ports:
      - "40010:80"
    depends_on:
      - simple_oidc_ids6_e2e_test_postgres
    environment:
      env: "Docker"

  simple_oidc_ids6_e2e_test_postgres:
    image: "postgres:13"
    container_name: simple_oidc_ids6_e2e_test_postgres
    env_file:
      .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
