name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: DEBUG

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
        cache: maven

    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./cicd/docker-compose-simple-oidc-ids6-e2e-test.yml"
        down-flags: "--volumes"
        services: |
          simple_oidc_ids6_e2e_test_app
          simple_oidc_ids6_e2e_test_postgres

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - name: File system info
      run: |
        echo "===========> github.workspace var: ${{ github.workspace }}"
        echo "===========> pwd:"
        pwd
        echo "===========> ls -hal:"
        ls -hal
        echo "===========> ls -hal /src:"
        ls -hal ./src
        echo "===========> ls -hal /target:"
        ls -hal ./target

    - name: Temporarily save jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-artifact
        path: ${{ github.workspace }}/target/stackjudge-${{ env.RELEASE_VERSION }}.jar
        retention-days: 1

#    - name: Copy created .jar for docker
#      run: |
#        cp ${{ github.workspace }}/target/stackjudge-${{ env.RELEASE_VERSION }}.jar ./stackjudge-docker-latest.jar
#
#    - name: Build docker image
#      run: |
#        docker build --tag stackjudge:latest .
#
#    - name: Save docker image
#      run: |
#        docker save -o stackjudge:${{ env.RELEASE_VERSION }}.docker stackjudge:latest
#
#    - name: Push do Cloudsmith
#      uses: cloudsmith-io/action@2f8578217e6fa9fe305977bb278057514bccd8ea
#      with:
#        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
#        command: push
#        format: docker
#        owner: stackjudge
#        repo: stackjudge_backend
#        republish: true
#        file: ./stackjudge:${{ env.RELEASE_VERSION }}.docker
